/**
 * Daily Devotion - Verse Fetcher
 * 
 * This script fetches the verse of the day from the ourmanna API.
 * It can be run standalone or imported as a module.
 * 
 * Usage:
 *   npx ts-node scripts/fetch_verse.ts
 * 
 * Or import in another file:
 *   import { fetchVerseOfTheDay } from './scripts/fetch_verse';
 */

import { getRandomBackupVerse, BackupVerse } from './backup_verses';

interface VerseDetails {
    text: string;
    reference: string;
    version: string;
    verseurl: string;
}

interface VerseResponse {
    verse: {
        details: VerseDetails;
        notice: string;
    };
}

export interface DailyVerse {
    text: string;
    reference: string;
    version: string;
    url: string;
    fetchedAt: string;
}

export interface TimeGreeting {
    period: 'morning' | 'afternoon' | 'evening' | 'night';
    greeting: string;
    hour: number;
}

const API_URL = 'https://beta.ourmanna.com/api/v1/get?format=json&order=daily';

/**
 * Fetches the verse of the day from the ourmanna API
 * @returns Promise<DailyVerse> The verse of the day
 */
export async function fetchVerseOfTheDay(): Promise<DailyVerse> {
    try {
        const response = await fetch(API_URL, {
            method: 'GET',
            headers: {
                'Accept': 'application/json',
                'User-Agent': 'DailyDevotionSkill/1.0'
            }
        });

        if (!response.ok) {
            throw new Error(`API responded with status: ${response.status}`);
        }

        const data = await response.json() as VerseResponse;

        if (!data.verse?.details?.text) {
            throw new Error('Invalid API response structure');
        }

        return {
            text: data.verse.details.text,
            reference: data.verse.details.reference,
            version: data.verse.details.version,
            url: data.verse.details.verseurl,
            fetchedAt: new Date().toISOString()
        };
    } catch (error) {
        console.warn('⚠️ Could not fetch verse from API, using backup verse');
        console.warn(`   Error: ${error instanceof Error ? error.message : 'Unknown error'}`);

        // Return a random backup verse
        const backup = getRandomBackupVerse();
        return {
            text: backup.text,
            reference: backup.reference,
            version: backup.version,
            url: `https://www.biblegateway.com/passage/?search=${encodeURIComponent(backup.reference)}`,
            fetchedAt: new Date().toISOString()
        };
    }
}

/**
 * Gets the time period and greeting based on current hour.
 * The farewell message should be generated by the bot based on context.
 * 
 * Time periods:
 * - morning: 5:00 AM - 11:59 AM
 * - afternoon: 12:00 PM - 4:59 PM  
 * - evening: 5:00 PM - 8:59 PM
 * - night: 9:00 PM - 4:59 AM
 */
export function getTimeGreeting(): TimeGreeting {
    const hour = new Date().getHours();

    if (hour >= 5 && hour < 12) {
        return { period: 'morning', greeting: 'Good morning', hour };
    } else if (hour >= 12 && hour < 17) {
        return { period: 'afternoon', greeting: 'Good afternoon', hour };
    } else if (hour >= 17 && hour < 21) {
        return { period: 'evening', greeting: 'Good evening', hour };
    } else {
        return { period: 'night', greeting: 'Good night', hour };
    }
}

/**
 * Formats the current date for display
 * @returns Formatted date string
 */
export function getFormattedDate(): string {
    const options: Intl.DateTimeFormatOptions = {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    };
    return new Date().toLocaleDateString('en-US', options);
}

// Main execution when run directly
async function main() {
    console.log('📖 Daily Devotion - Verse Fetcher\n');
    console.log(`📅 ${getFormattedDate()}\n`);

    const greeting = getTimeGreeting();
    console.log(`${greeting.greeting}! (${greeting.period})\n`);

    console.log('Fetching verse of the day...\n');

    const verse = await fetchVerseOfTheDay();

    console.log('━'.repeat(50));
    console.log('\n📜 Today\'s Verse:\n');
    console.log(`  "${verse.text}"`);
    console.log(`\n  — ${verse.reference} (${verse.version})`);
    console.log('\n' + '━'.repeat(50));
    console.log('\n✨ Generate a contextual farewell based on the time period and verse.\n');
}

// Run if this is the main module
const isMainModule = require.main === module ||
    process.argv[1]?.includes('fetch_verse');

if (isMainModule) {
    main().catch(console.error);
}
